# Only enable specific rules
only_rules:
  - todo        # TODO and FIXME comments
  - empty_count # Prefer isEmpty over count == 0
  - toggle_bool # Prefer someBool.toggle() over someBool = !someBool
  
# Include only specific directories with correct path
included:
  - iOS/Scenes/ConvoAI/ConvoAI  # Path as shown in error messages
  
# Excluded paths
excluded:
  - Pods
  - dotLottie-iOS
  - "*/Frameworks"
  - "**/Generated"
  - Carthage
  - fastlane

# Output format
reporter: "xcode" # Detailed output with file names and line numbers 