# Enable only specific rules - we will add more gradually
only_rules: [
  identifier_name  # Variable naming rules
]

# Excluded paths
excluded:
  - Pods
  - dotLottie-iOS
  - "*/Frameworks"
  - "**/Generated"
  - Carthage
  - fastlane 