# Enable only specific rules - we will add more gradually
only_rules: []

# Enable analyzer rules
analyzer_rules:
  - unused_declaration  # Check for unused variables, functions, etc.

# Excluded paths
excluded:
  - Pods
  - dotLottie-iOS
  - "*/Frameworks"
  - "**/Generated"
  - Carthage
  - fastlane 