# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'Agent-global' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AlamofireImage', '~> 4.3'
  pod 'SSZipArchive'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'ZSwiftBaseLib', '0.1.6.2'
#  pod 'AgoraRtcEngine_iOS', :path => 'sdk.podspec'
  pod 'AgoraRtcEngine_iOS', '4.6.4'
  pod 'agent-client-toolkit-swift', :podspec => 'ThirdParty/AgentClientToolkit/agent-client-toolkit-swift.podspec.json'
  #pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

  pod 'Common', :path => 'Common'

  # Agents
  pod 'ConvoAI', :path => 'Scenes/ConvoAI/ConvoAI'
  pod 'IoT', :path => 'Scenes/ConvoAI/IoT'
  pod 'BLEManager', :path => 'Scenes/ConvoAI/BLEManager'

  pod 'Kingfisher'

  pod 'Firebase/Crashlytics', '12.14.0'
  pod 'Agora-Rtm', '2.3.0', :subspecs => ['RtmKit']

end

post_install do |installer|
  resource_url = "https://download.agora.io/demo/release/Convo_AI_Demo_v2.0.0_Resource.zip"
  download_path = "#{Dir.pwd}/Agent/Resources/Convo_AI_Demo_v2.0.0_Resource.zip"
  extract_path = "#{Dir.pwd}/Agent/Resources"
  video_names = %w[ball_video_start.mp4 ball_video_rotating.mp4]

  unless video_names.all? { |name| File.file?(File.join(extract_path, name)) }
    Pod::UI.puts "Downloading Convo AI Demo resources..."
    unless system('curl', '-fL', resource_url, '-o', download_path)
      raise Pod::Informative, "Resource download failed"
    end
    unless system('unzip', '-j', '-o', download_path,
                  *video_names.map { |name| "*/#{name}" }, '-d', extract_path)
      raise Pod::Informative, "Resource extraction failed"
    end
    File.delete(download_path)
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Additional post-install configuration can be added here.
    end
  end
end
