name: iOS Code Style Check

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'iOS/**'
      - '!**/Pods/**'
      - '!iOS/dotLottie-iOS/**'
      - '!**/*.md'
      - '!**/*.txt'
      - '!**/*.png'
      - '!**/*.jpg'


jobs:
  swiftlint:
    name: SwiftLint Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        working-directory: ./iOS
        args: --strict --reporter github-actions-logging
